[package]
name = "my-wallet-api"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]
